version: '3.2'

services:
  db:
    image: postgres:10.12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    volumes:
      - postdb-data:/var/lib/postgresql/data
  nginx:
    image: nginx:1.17.9-alpine
    ports:
      - 5000:8080
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  api:
    image: portal/api
    build: .
    restart: always
    depends_on:
      - db
    # command: node --max_old_space_size=15500 dist/src/main.js
    command: npm run start:dev
    volumes:
      - ./src:/home/app/src
      - ./dist:/home/app/dist
volumes:
  postdb-data:
    driver: local
